revert: temp fixed for compilation error
   ERROR: boot size (17649664) is 99.01% of limit (17825792)

Change-Id: Idc84f7c48a7a70c94eae7a9002af29595e80e27f
Signed-off-by: ZION959 <ziontran@gmail.com> (reverted from commit 1dba1420685d0e658c2808b16449dc7fe16f8ada)